In [3]:
import numpy as np

In [4]:
names_data = np.array(['Vinay','Dovvari','keerthana','hmridha','Afsan','raja','shailja', 'Biven'])

In [ ]:
names_data.reshape(4,2)

array([['Vinay', 'Dovvari'],
       ['keerthana', 'hmridha'],
       ['Afsan', 'raja'],
       ['shailja', 'Biven']], dtype='<U9')

In [5]:
# infer

# wer i want the number of columns as 2 only
names_data.reshape(4,2)

array([['Vinay', 'Dovvari'],
       ['keerthana', 'hmridha'],
       ['Afsan', 'raja'],
       ['shailja', 'Biven']], dtype='<U9')

In [ ]:
data = np.arange(0,1000).reshape(5,10,10,2)

In [ ]:
data.shape

(5, 10, 10, 2)

In [ ]:
# 2 dim where rows == 20
data.reshape(20,-1).shape

(20, 50)

In [ ]:
# 3d matrix 2,5
data.reshape(2,2,-1).shape

(2, 2, 250)

In [ ]:
# transpose of matrix

data = names_data.reshape(4,2)

In [ ]:
data

array([['Vinay', 'Dovvari'],
       ['keerthana', 'hmridha'],
       ['Afsan', 'raja'],
       ['shailja', 'Biven']], dtype='<U9')

In [ ]:
data.shape

(4, 2)

In [ ]:
data.T

array([['Vinay', 'keerthana', 'Afsan', 'shailja'],
       ['Dovvari', 'hmridha', 'raja', 'Biven']], dtype='<U9')

In [ ]:
# flatten ravel
- it converts the higer dimension matrix to vector form

In [ ]:
data = np.arange(0,1000).reshape(5,10,10,2)

In [ ]:
data.shape

(5, 10, 10, 2)

In [ ]:
data.flatten()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
data.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
# basic operation

# element wise - shape of both the matrix should be same

In [ ]:
a = np.array([10,20,30,40])
b = np.array([5,10,15,20])

In [ ]:
a+b

array([15, 30, 45, 60])

In [ ]:
a-b

array([ 5, 10, 15, 20])

In [ ]:
a/b

array([2., 2., 2., 2.])

In [ ]:
a*b

array([ 50, 200, 450, 800])

In [ ]:
a%2

array([0, 0, 0, 0])

In [ ]:
a<=25

array([ True,  True, False, False])

In [ ]:
# matrix multiplcation

a = n*m
b = m*p
c = n*p

In [ ]:
a = 2*6
b = 6*5
c = 2*5

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[5,1],[5,1],[5,1]])

In [ ]:
a.shape

(3, 3)

In [ ]:
b.shape

(3, 2)

In [ ]:
a.dot(b)

array([[ 30,   6],
       [ 75,  15],
       [120,  24]])

In [ ]:
a = np.array([10,20,30,40])
b = np.array([5,10,15,20])

In [ ]:
a+b

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
# Unary operations

In [ ]:
a = np.array([10,20,30,40])

In [ ]:
# sum
a.sum()

100

In [ ]:
# min
a.min()

10

In [ ]:
# max
a.max()

40

In [ ]:
a = np.arange(0,25).reshape(5,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a.sum()

300

In [ ]:
# cal the sum of all the rows

"""
axis = 1 -- rowise
axis = 0 -- columnwise

"""
a.sum(axis=1)

array([ 10,  35,  60,  85, 110])

In [ ]:
# cal the sum of all the columns

"""
axis = 1 -- rowise
axis = 0 -- columnwise

"""
a.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
# cal the min of all the columns

a.min(axis=0)[0]

array([0, 1, 2, 3, 4])

In [ ]:
a.max(axis=0)

array([20, 21, 22, 23, 24])

In [ ]:
a.min(axis=1)

array([ 0,  5, 10, 15, 20])

In [ ]:
a.max(axis=1)

array([ 4,  9, 14, 19, 24])

In [ ]:
# indexing and slicing

In [ ]:
a = np.arange(5)*2

In [ ]:
a

array([0, 2, 4, 6, 8])

In [ ]:
#indexing

In [ ]:
a[0]

0

In [ ]:
a[-1]

8

In [ ]:
a = np.arange(0,25).reshape(5,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a[2][2]

12

In [ ]:
a[-1][-2]

23

In [ ]:
# slicing

In [ ]:
a = np.arange(5)*2

In [ ]:
a

array([0, 2, 4, 6, 8])

In [ ]:
a[1:4:-1]

array([], dtype=int64)

In [ ]:
a[1:4:2]

array([2, 6])

In [ ]:
a = np.arange(0,25).reshape(5,5)

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a[2][2:4]

array([12, 13])

In [ ]:
a[row,columns]

In [ ]:
a[2:3,2:4]

array([[12, 13]])

In [ ]:
12 13
17 18

In [ ]:
a[2:4,2:4]

array([[12, 13],
       [17, 18]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
5,  6,  7,  8,  9
10, 11, 12, 13, 14
15, 16, 17, 18, 19

In [ ]:
6   8
11  13
16  18

In [ ]:
a[1:4,1::2]

array([[ 6,  8],
       [11, 13],
       [16, 18]])

In [ ]:
a[1:4,1::2]

array([[ 6,  8],
       [11, 13],
       [16, 18]])

In [ ]:
a[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [ ]:
a[0:len(a):1]

In [ ]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a[1:4:2,0:3:2]

array([[ 5,  7],
       [15, 17]])

In [ ]:
[5, 6, 7, 8, 9]
[15, 16, 17, 18, 19]

In [ ]:
a = [[ 0,  1,  2,  3,  4],[ 5,  6,  7,  8,  9],[10, 11, 12, 13, 14],[15, 16, 17, 18, 19],[20, 21, 22, 23, 24]]

In [ ]:
a = np.arange(0,25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
1  4
11 14
21 24

In [ ]:
a[0:5:2]

array([[ 1,  4],
       [11, 14],
       [21, 24]])

In [ ]:
a = np.arange(0,24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[1:6:2,0:3:2]

array([[ 4,  6],
       [12, 14],
       [20, 22]])